{
 "title": "ESMR 5 Meter",
 "time": { "from": "2020-02-18T03:53:49.616Z", "to": "2020-02-18T07:54:30.237Z" },
 "panels": [
  {
   "title": "Elektra gebruik dal",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum(rate(p1_total_electricity_used_rate_1[3m])) * 1000"
    }
   ]
  },
  {
   "title": "Elektra gebruik piek",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum(rate(p1_total_electricity_used_rate_2[3m])) * 1000"
    }
   ]
  },
  {
   "title": "Elektra geleverd dal",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "increase(p1_total_electricity_provided_rate_1[2m])",
     "legendFormat": "KWh"
    }
   ]
  },
  {
   "title": "Elektra geleverd dal",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "increase(p1_total_electricity_provided_rate_1[2m])",
     "legendFormat": "KWh"
    }
   ]
  },
  {
   "title": "Gebruik gas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "m3" }
   ],
   "targets": [
    {
     "expr": "sum(rate(p1_total_gas_used[3m]))",
     "legendFormat": "KWh"
    }
   ]
  }
 ]
}